<?php

declare(strict_types=1);

namespace Sloth\Model\Registrars;

use Composer\ClassMapGenerator\ClassMapGenerator;
use Sloth\Core\Application;
use Sloth\Model\Model;
use Sloth\Model\Proxy\CurrentModelProxy;
use Sloth\Model\Resolvers\ModelsResolver;

/**
 * Registrar for WordPress post type registration.
 *
 * Discovers all Model subclasses via ModelsResolver and registers them
 * as WordPress post types.
 *
 * ## Registration flow per model
 *
 * 1. Skip if $modelClass::$register is false
 * 2. Merge Sloth defaults with model $options
 * 3. For existing post types (e.g. WP Core 'page'): rescue rewrite settings
 *    BEFORE unregistering — otherwise rewrite: false is lost
 * 4. Build labels from $modelClass::$labels or $modelClass::$names
 * 5. Set menu icon from $modelClass::$icon if not null
 * 6. Unregister existing post type (if present)
 * 7. Register with WordPress
 * 8. Register admin column hooks
 * 9. Register model class for newFromBuilder() resolution
 * 10. Configure Layotter
 *
 * flush_rewrite_rules() is called once after all models are registered.
 *
 * @since 1.0.0
 * @see \Sloth\Model\Model
 */
class ModelRegistrar
{
    /**
     * The directory where model classes are located.
     *
     * @var string
     */
    protected static string $dir = 'Model';
    /**
     * Registered models mapping post type slug to class name.
     *
     * @since 1.0.0
     * @var array<string, class-string<Model>>
     */
    protected array $models = [];

    /**
     * Constructor.
     *
     * @param Application $app The application container instance.
     * @since 1.0.0
     *
     */
    public function __construct(private Application $app)
    {
    }

    /**
     * Discover and register all models with WordPress.
     *
     * Called on the WordPress 'init' hook via ModelServiceProvider.
     *
     * @since 1.0.0
     */
    public function init(): void
    {
        $manifest = app()->path('cache') . '/models.manifest.php';

        if (app()->isLocal() || !app('files')->exists($manifest)) {
            $this->registerModels($manifest);
        }

        require_once $manifest;

        collect(app()->get('sloth.models'))->each(function ($className, $postType) {
            #$instance = new $className;
            #$instance->registerColumnHooks();
            $this->configureLayotter($className, $postType);
        });
    }

    /**
     * Write the models manifest file to the cache directory.
     *
     * The manifest is a plain PHP file that when included performs all class
     * loading and post type registration with zero discovery overhead.
     * Opcache caches it after the first include — as fast as it gets.
     *
     * Delete the file to force regeneration on the next request.
     *
     * @since 1.0.0
     */
    protected function writeManifest(string $path, array $lines): void
    {
        try {
            app('files')->ensureDirectoryExists(dirname($path));
            app('files')->put($path, implode("\n", $lines));
        } catch (\Throwable) {
            // Non-fatal — manifest is an optimisation, not a requirement
        }
    }

    /**
     * Register all discovered models as WordPress post types.
     *
     * @since 1.0.0
     */
    protected function registerModels($manifest): void
    {
        $generator = new ClassMapGenerator;
        $mainfestLines = [
            '<?php',
            '// Generated by Sloth — delete to regenerate.',
            '',
        ];
        $models = [];
        collect([
            app()->path(static::$dir),
            app()->path(static::$dir, 'theme'),
        ])
            ->filter(fn($path) => app('files')->isDirectory($path))
            ->each(function ($path) use ($generator) {
                $generator->scanPaths($path);
            });
        $classMap = $generator->getClassMap();
        $classMap->sort();
        collect($classMap->getMap())
            ->each(function ($file, $modelClass) use (&$mainfestLines, &$models) {
                // 1. Skip if registration is disabled
                if (!$modelClass::$register) {
                    return;
                }

                $instance = new $modelClass();
                if (!is_subclass_of($instance, Model::class)) {
                    return;
                }

                $postType = $instance->getPostType();

                $args = $modelClass::$options;

                $args['labels'] = $this->buildLabels($modelClass, $postType);

                $args['admin_cols'] = $this->buildAdminCols($modelClass);

                if ($modelClass::$icon !== null) {
                    $args['menu_icon'] = 'dashicons-' . preg_replace('/^dashicons-/', '', $modelClass::$icon);
                }


                $mainfestLines[] = '/* registering post-type ' . $postType . '*/';
                $mainfestLines[] = 'require_once ' . var_export($file, true) . ';';
                $mainfestLines[] = '\register_extended_post_type("' . $postType . '",' . var_export($args, true) . ');';
                $mainfestLines[] = '';

                $models[$postType] = $modelClass;
            });
        $mainfestLines[] = 'app()->instance("sloth.models", ' . var_export($models, true) . ');';
        $this->writeManifest($manifest, $mainfestLines);
    }

    /**
     * Build WordPress post type labels for a model.
     *
     * Only sets labels that contain the post type name — WordPress generates
     * the remaining labels automatically from name and singular_name, correctly
     * translated into the active WordPress language.
     *
     * If $modelClass::$labels is set, those are used directly (with translation).
     * Otherwise labels are auto-generated from $modelClass::$names['singular']
     * and $modelClass::$names['plural'].
     *
     * Falls back to ucfirst($postType) for singular and singular + 's' for plural.
     *
     * @param class-string<Model> $modelClass The model class name.
     * @param string $postType The post type slug.
     * @return array<string, string> WordPress post type labels.
     * @since 1.0.0
     *
     */
    protected function buildLabels(string $modelClass, string $postType): array
    {
        $labels = $modelClass::$labels;
        $names = $modelClass::$names;

        $singular = $names['singular'] ?? ucfirst($postType);
        $plural = $names['plural'] ?? $singular . 's';

        return array_merge([
            'name' => __($plural),
            'singular_name' => __($singular),
            'menu_name' => __($plural),
            'name_admin_bar' => __($singular),
        ], $labels);
    }


    /**
     * Translate $admin_columns to extended-cpts admin_cols format.
     *
     * Preserves full backwards compatibility — theme developers keep using
     * $admin_columns and get{Column}Column() methods unchanged.
     *
     * @param class-string<Model> $modelClass
     * @return array<string, array<string, mixed>>
     * @since 1.0.0
     */
    protected function buildAdminCols(string $modelClass): array
    {
        $adminCols = [];

        foreach ($modelClass::$admin_columns as $key => $label) {
            if (in_array($key, $modelClass::$admin_columns_hidden ?? [], true)) {
                continue;
            }

            $method = 'get' . ucfirst($key) . 'Column';

            if (method_exists($modelClass, $method)) {
                debug($method, $modelClass);
                $adminCols[$key] = [
                    'title' => $label,
                    'function' => [CurrentModelProxy::class, $method . 'Echo'],
                ];
            } else {
                $adminCols[$key] = [
                    'title' => $label,
                    'meta_key' => $key,
                ];
            }
        }

        return $adminCols;
    }

    /**
     * Configure Layotter page builder integration for a model.
     *
     * Reads $modelClass::$layotter — falls back to false if not declared.
     *
     * - false → Layotter disabled for this post type
     * - true  → Layotter enabled with default settings
     * - array → Layotter enabled with custom settings (e.g. allowed_row_layouts)
     *
     * Skips silently if Layotter is not bound in the container.
     *
     * @param class-string<Model> $modelClass The model class name.
     * @param string $postType The post type slug.
     * @since 1.0.0
     *
     */
    protected function configureLayotter(string $modelClass, string $postType): void
    {
        try {
            $layotter = $modelClass::$layotter;
            $layotterService = $this->app['layotter'];
        } catch (\Throwable) {
            return;
        }

        if ($layotter === false) {
            $layotterService->disable_for_post_type($postType);
            return;
        }

        $layotterService->enable_for_post_type($postType);

        if (is_array($layotter) && isset($layotter['allowed_row_layouts'])) {
            $layotterService->set_layouts_for_post_type(
                $postType,
                $layotter['allowed_row_layouts']
            );
        }
    }

    /**
     * Get all registered models.
     *
     * @return array<string, class-string<Model>> Post type slug to class name mapping.
     * @since 1.0.0
     *
     */
    public function getModels(): array
    {
        return $this->models;
    }
}
