<?php

declare(strict_types=1);

namespace Sloth\Support;

use Composer\ClassMapGenerator\ClassMapGenerator;
use Sloth\Core\Application;

/**
 * Base class for manifest-based WordPress type registration.
 *
 * Provides the common discovery + manifest pattern used by ModelRegistrar
 * and TaxonomyRegistrar:
 *
 * - On first request (or in development): scan directories with ClassMapGenerator,
 *   filter classes, build args, write manifest.
 * - On every request: require_once manifest — no scanning, no Reflection.
 *
 * Subclasses implement the type-specific logic:
 * - $dir, $subclassOf, $manifestName
 * - getSlug() — post type name or taxonomy slug
 * - buildArgs() — registration args array
 * - buildNames() — singular/plural for extended-cpts
 * - toManifestLine() — the register_extended_*() call as a string
 * - toContainerLine() — stores registered types in the container
 * - afterManifest() — anything that runs every request but can't be in the manifest
 *
 * @since 1.0.0
 */
abstract class AbstractRegistrar
{
    /** Subdirectory to scan relative to app/ and theme/. */
    protected static string $dir;

    /** Only classes extending this are registered. */
    protected static string $subclassOf;

    /** Filename for the generated manifest in the cache directory. */
    protected static string $manifestName;

    public function __construct(protected Application $app)
    {
    }

    /**
     * Discover and register all types with WordPress.
     *
     * In development: always runs full discovery.
     * In production: uses manifest if present, otherwise generates it.
     *
     * @since 1.0.0
     */
    public function init(): void
    {
        $manifest = app()->path('cache') . '/' . static::$manifestName;
        app()->instance('sloth.models', []);
        app()->instance('sloth.taxonomies', []);
        if (app()->isLocal() || !app('files')->exists($manifest)) {
            $this->run($manifest);
        }

        require_once $manifest;

        $this->afterManifest();
    }

    /**
     * Scan directories, build args, and write the manifest.
     *
     * @since 1.0.0
     */
    protected function run(string $manifest): void
    {
        $generator = new ClassMapGenerator();
        collect([
            app()->path(static::$dir),
            app()->path(static::$dir, 'theme'),
        ])
            ->filter(fn($path) => app('files')->isDirectory($path))
            ->each(fn($path) => $generator->scanPaths($path));

        $classMap = $generator->getClassMap();
        $classMap->sort();

        $registered = [];
        $manifestLines = [
            '<?php',
            '// Generated by Sloth — delete to regenerate.',
            '',
        ];

        collect($classMap->getMap())
            ->each(function ($file, $class) use (&$manifestLines, &$registered) {
                require_once $file;
                if (!$class::$register) {
                    return;
                }

                $instance = new $class();

                if (!is_subclass_of($instance, static::$subclassOf)) {
                    return;
                }

                $slug = $this->getSlug($class, $instance);
                $args = $this->buildArgs($class, $instance);
                $names = $this->buildNames($class, $slug);

                $manifestLines[] = '/* ' . $slug . ' */';
                $manifestLines[] = 'require_once ' . var_export($file, true) . ';';
                $manifestLines[] = $this->toManifestLine($slug, $class, $args, $names);
                $manifestLines[] = '';

                $registered[$slug] = $class;
            });

        $manifestLines[] = $this->toContainerLine($registered);

        $this->writeManifest($manifest, $manifestLines);
    }

    /**
     * Get the WordPress slug for an instance (post type name or taxonomy name).
     *
     * @param class-string $class
     * @since 1.0.0
     */
    abstract protected function getSlug(string $class, object $instance): string;

    /**
     * Build the registration args for a class.
     *
     * @param class-string $class
     * @return array<string, mixed>
     * @since 1.0.0
     */
    abstract protected function buildArgs(string $class, object $instance): array;

    /**
     * Build the names array for register_extended_*().
     *
     * @param class-string $class
     * @return array{singular: string, plural: string}
     * @since 1.0.0
     */
    abstract protected function buildNames(string $class, string $slug): array;

    /**
     * Return the PHP line that registers the type with WordPress.
     *
     * Written into the manifest. Must produce the same effect when executed.
     *
     * @param class-string $class
     * @param array<string, mixed> $args
     * @param array{singular: string, plural: string} $names
     * @since 1.0.0
     */
    abstract protected function toManifestLine(string $slug, string $class, array $args, array $names): string;

    /**
     * Return the PHP line that stores registered types in the container.
     *
     * Written once at the end of the manifest.
     *
     * @param array<string, class-string> $registered Map of slug => class name
     * @since 1.0.0
     */
    abstract protected function toContainerLine(array $registered): string;

    /**
     * Called on every request after the manifest is included.
     *
     * Override for things that can't be in the manifest —
     * metabox registration, etc.
     *
     * @since 1.0.0
     */
    protected function afterManifest(): void
    {
    }

    /**
     * Write the manifest to the cache directory.
     *
     * Non-fatal — manifest is an optimisation, not a requirement.
     *
     * @since 1.0.0
     */
    protected function writeManifest(string $path, array $lines): void
    {
        try {
            app('files')->ensureDirectoryExists(dirname($path));
            app('files')->put($path, implode("\n", $lines));
        } catch (\Throwable) {
            // Non-fatal
        }
    }
}
