<?php

declare(strict_types=1);

namespace Sloth\Support\Manifest;

/**
 * Writes a manifest PHP file from a file map.
 *
 * The manifest contains:
 * 1. require_once for every discovered file
 * 2. Any extra lines provided by the caller (registration calls, class definitions, etc.)
 * 3. app()->instance() calls for container bindings
 *
 * The manifest is a plain PHP file — Opcache will cache it after the first include.
 * Delete the file to force regeneration on the next request.
 *
 * @since 1.0.0
 */
class ManifestWriter
{
    /**
     * @param string                      $path              Absolute path to write the manifest to.
     * @param array<string, string>       $map               Identifier => file path map from a Finder.
     * @param array<string, list<string>> $extraLines        Extra PHP lines per identifier.
     * @param array<string, mixed>        $containerBindings Key => value pairs for app()->instance().
     */
    public function write(
        string $path,
        array $map,
        array $extraLines = [],
        array $containerBindings = [],
    ): void {
        $lines = collect([
            '<?php',
            '// Generated by Sloth — delete to regenerate.',
            '',
        ]);

        collect($map)->each(function ($file, $identifier) use ($lines, $extraLines) {
            $lines->push('require_once ' . var_export($file, true) . ';');

            collect($extraLines[$identifier] ?? [])->each(fn($line) => $lines->push($line));

            $lines->push('');
        });

        collect($containerBindings)->each(function ($value, $key) use ($lines) {
            $lines->push('app()->instance(' . var_export($key, true) . ', ' . var_export($value, true) . ');');
        });

        try {
            app('files')->ensureDirectoryExists(dirname($path));
            app('files')->put($path, $lines->implode("\n"));
        } catch (\Throwable) {
            // Non-fatal — manifest is an optimisation, not a requirement
        }
    }
}
