<?php

declare(strict_types=1);

namespace Sloth\Support\Manifest;

use Illuminate\Filesystem\Filesystem;

/**
 * Writes a manifest PHP file from a file map.
 *
 * Generates a plain PHP manifest file that Opcache can cache after the first
 * include. The manifest serves two purposes:
 *
 * 1. **Autoloading** — `require_once` statements ensure all discovered files
 *    are loaded on every request with zero discovery overhead.
 * 2. **Entry data** — a `return` statement provides structured data (computed
 *    at build time) that Registrars consume to perform WordPress registrations.
 *
 * ## Generated manifest format
 *
 * ```php
 * <?php
 * // Generated by Sloth — delete to regenerate.
 *
 * require_once '/abs/path/NewsModel.php';
 * class TeaserModule extends \Sloth\Module\LayotterElement { static $module = '\\App\\Module\\TeaserModule'; }
 * \Layotter::register_element('teaser-module', 'TeaserModule');
 *
 * return [
 *     '\\App\\Model\\NewsModel' => [
 *         'postType' => 'news',
 *         'args'     => ['public' => true, ...],
 *         'names'    => ['singular' => 'News', 'plural' => 'News', 'slug' => 'news'],
 *     ],
 * ];
 * ```
 *
 * ## Write failures
 *
 * If the manifest cannot be written (permission issues, missing directories),
 * the error is silently swallowed. Manifests are an optimisation — the application
 * still functions without them, albeit with discovery overhead on every request.
 *
 * @since 1.0.0
 */
class ManifestWriter
{
    /**
     * Creates a new ManifestWriter instance.
     *
     * @param Filesystem $files The filesystem abstraction used for directory creation and file writing.
     */
    public function __construct(
        private readonly Filesystem $files,
    ) {}

    /**
     * Write the manifest file to the given path.
     *
     * Generates a PHP file containing require_once statements for every discovered
     * file, optional extra lines (e.g. Layotter class definitions), and a return
     * statement with the serialized entry data.
     *
     * @param string                      $path       Absolute path where the manifest file will be written.
     * @param array<string, string>       $map        Identifier => absolute file path map produced by a Finder.
     * @param array<string, list<string>> $extraLines PHP code lines to embed after each file's require_once.
     *                                                Keys must match identifiers from $map.
     * @param array<string, mixed>        $entries    Structured data returned by the manifest. Consumed by
     *                                                Registrars to perform WordPress registrations without
     *                                                recomputing arguments at runtime.
     *
     * @since 1.0.0
     */
    public function write(
        string $path,
        array $map,
        array $extraLines = [],
        array $entries = [],
    ): void {
        $lines = collect([
            '<?php',
            '// Generated by Sloth — delete to regenerate.',
            '',
        ]);

        collect($map)->each(function ($file, $identifier) use ($lines, $extraLines) {
            $lines->push('require_once ' . var_export($file, true) . ';');

            collect($extraLines[$identifier] ?? [])->each(fn($line) => $lines->push($line));

            $lines->push('');
        });

        $lines->push('return ' . var_export($entries, true) . ';');

        try {
            $this->files->ensureDirectoryExists(dirname($path));
            $this->files->put($path, $lines->implode("\n"));
        } catch (\Throwable) {
            // Non-fatal — manifest is an optimisation, not a requirement
        }
    }
}
