<?php

declare(strict_types=1);

namespace Sloth\Support\Manifest;

use Illuminate\Filesystem\Filesystem;

/**
 * Writes a manifest PHP file from a file map.
 *
 * The manifest contains:
 * 1. require_once for every discovered file
 * 2. Any extra lines provided by the caller (registration calls, class definitions, etc.)
 *
 * The manifest is a plain PHP file — Opcache will cache it after the first include.
 * Delete the file to force regeneration on the next request.
 *
 * @since 1.0.0
 */
class ManifestWriter
{
    public function __construct(
        private readonly Filesystem $files,
    ) {}

    /**
     * @param string                      $path       Absolute path to write the manifest to.
     * @param array<string, string>       $map        Identifier => file path map from a Finder.
     * @param array<string, list<string>> $extraLines Extra PHP lines per identifier.
     */
    public function write(
        string $path,
        array $map,
        array $extraLines = [],
    ): void {
        $lines = collect([
            '<?php',
            '// Generated by Sloth — delete to regenerate.',
            '',
        ]);

        collect($map)->each(function ($file, $identifier) use ($lines, $extraLines) {
            $lines->push('require_once ' . var_export($file, true) . ';');

            collect($extraLines[$identifier] ?? [])->each(fn($line) => $lines->push($line));

            $lines->push('');
        });

        try {
            $this->files->ensureDirectoryExists(dirname($path));
            $this->files->put($path, $lines->implode("\n"));
        } catch (\Throwable) {
            // Non-fatal — manifest is an optimisation, not a requirement
        }
    }
}
