<?php

declare(strict_types=1);

namespace Sloth\Core\Manifest;

use Sloth\Core\ServiceProvider;
use Sloth\Support\Manifest\AbstractManifestBuilder;
use Sloth\Support\Manifest\ComposerFinder;
use Sloth\Support\Manifest\FinderInterface;

/**
 * Builds a manifest for vendor Composer package ServiceProvider discovery.
 *
 * Parses vendor/composer/installed.json to find packages that declare
 * Sloth service providers via extra.laravel.providers (Laravel-compatible format).
 *
 * ## How it works
 *
 * 1. ComposerFinder reads installed.json and extracts provider class names.
 * 2. The manifest caches these provider class names (no require_once needed —
 *    Composer autoloads the files).
 * 3. Application::registerProviders() reads the manifest and registers each
 *    discovered provider with the application container.
 *
 * ## Manifest format
 *
 * ```php
 * <?php
 * // Generated by Sloth — delete to regenerate.
 *
 * return [
 *     '\\Vendor\\Package\\ServiceProvider',
 *     '\\Another\\Package\\ServiceProvider',
 * ];
 * ```
 *
 * ## Package declaration (vendor composer.json)
 *
 * ```json
 * {
 *     "name": "vendor/package",
 *     "extra": {
 *         "laravel": {
 *             "providers": ["Vendor\\Package\\ServiceProvider"]
 *         }
 *     }
 * }
 * ```
 *
 * ## Ignoring packages (app/theme composer.json)
 *
 * ```json
 * {
 *     "extra": {
 *         "laravel": {
 *             "dont-discover": ["vendor/package"]
 *         }
 *     }
 * }
 * ```
 *
 * ## No require_once
 *
 * This builder overrides requireFiles() to return false because Composer
 * handles autoloading. The manifest only serves as a cached list of
 * provider class names.
 *
 * @since 1.0.0
 * @see \Sloth\Support\Manifest\AbstractManifestBuilder For the base class lifecycle
 * @see \Sloth\Support\Manifest\ComposerFinder           For installed.json parsing
 * @see \Sloth\Core\Application::registerProviders()     For provider registration
 */
class VendorProviderManifestBuilder extends AbstractManifestBuilder
{
    /**
     * Disable require_once in the manifest.
     *
     * Composer handles autoloading for vendor packages — the manifest
     * only caches the list of provider class names.
     *
     * @return bool Always false for vendor package discovery.
     * @since 1.0.0
     */
    #[\Override]
    protected function requireFiles(): bool
    {
        return false;
    }

    /**
     * Return the finder for Composer package discovery.
     *
     * Uses ComposerFinder to parse vendor/composer/installed.json
     * and extract provider class names from extra.laravel.providers.
     *
     * @return FinderInterface The configured ComposerFinder.
     * @since 1.0.0
     */
    #[\Override]
    protected function finder(): FinderInterface
    {
        return new ComposerFinder($this->app);
    }

    /**
     * Return a flat array of discovered provider class names.
     *
     * The map from ComposerFinder is [provider-class => package-name].
     * We return a flat list of provider class names for easy iteration.
     *
     * @param array<string, string> $map Provider class name => package name.
     * @return list<class-string<ServiceProvider>> Flat array of provider class names.
     * @since 1.0.0
     */
    #[\Override]
    protected function entries(array $map): array
    {
        return array_keys($map);
    }
}
